# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6bde05e1cc7966cb924ee1b260082f126100dd3d7c87214a5141202d2a82b315c29c54ac39b88ebc475ea681fccb5f67b6ce9cb395421100a7d2ef7632dc87e1

test:
  secret_key_base: eec13f639398a68313c25dbec9be178aab010ee2fb86ee30e040a31b1a067ca25da9fc3b4189d1c9731d1c680440c729ed8b0970b14fdb144fa82b8b3865821d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
